print("Hello")
print("Here's a picture of a dog")
print(" o____")
print("  ||||")
print("My favorite animal is sheep")
print("o-###-")
print("  | |   #")
print("I live in Glasgow")
print("    _|_     ")
print("   |   |")
print("   |#  |____")
print("   |   |    |")
print("   |  #|  # |")
print("  _|___|_#__|_")
born = input("What year were you born? ")
if len(born) != 4:
    print("Rerun the program and make sure to enter born year in YYYY format")
else:
    age = 2025 - int(born)
    print(f'you will be {age} years old in 2025')
    print(' /\ '*5)
    print('   \/'*5)
    print(f'Your age in dog years is {age*7}')
